@extends('layouts.app')
@section('title','Đổi trả & hoàn tiền')
@section('content')
<link rel="stylesheet" href="{{ asset('css/orders-pro-v2.css') }}?v={{ @filemtime(public_path('css/orders-pro-v2.css')) ?: time() }}">
<script defer src="{{ asset('js/orders-pro-v2.js') }}?v={{ @filemtime(public_path('js/orders-pro-v2.js')) ?: time() }}"></script>
@php
$statusLabels=['draft'=>'Nháp','revision_requested'=>'Yêu cầu chỉnh sửa','pending_sales_manager'=>'Chờ Sales Manager','pending_accounting'=>'Chờ kế toán','pending_management'=>'Chờ BGĐ','approved_waiting_return'=>'Chờ hàng về','return_in_transit'=>'Đang thu hồi','received'=>'Kho đã nhận','inspecting'=>'Đang kiểm tra','inspected'=>'Đã kiểm tra','stocked_in'=>'Đã nhập hoàn','pending_refund'=>'Chờ tài chính','completed'=>'Hoàn tất','rejected'=>'Từ chối','cancelled'=>'Đã hủy'];
$typeLabels=['return'=>'Hoàn trả','exchange'=>'Đổi hàng','recall'=>'Thu hồi','cancel'=>'Hủy trước xuất kho'];
@endphp
<div class="erp-page"><div class="erp-container">
<div class="erp-page-head"><div><div class="erp-breadcrumb"><a href="{{ route('orders.index') }}">Đơn hàng</a><span>/</span><strong>Đổi trả & hoàn tiền</strong></div><h1 class="erp-title">Đổi trả & hoàn tiền</h1><div class="erp-subtitle">Theo dõi hủy đơn, thu hồi, hoàn hàng, xử lý kho và hoàn tiền.</div></div><div class="erp-head-actions"><a class="erp-btn" href="{{ route('orders.index') }}"><i class="bi bi-arrow-left"></i> Đơn hàng</a></div></div>
@if(session('success'))<div class="erp-alert erp-alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="erp-alert erp-alert-danger">{{ session('error') }}</div>@endif
<div class="erp-stats">
<div class="erp-stat blue"><div class="erp-stat-icon"><i class="bi bi-arrow-left-right"></i></div><div><div class="erp-stat-label">Tổng yêu cầu</div><div class="erp-stat-value">{{ number_format($stats['total'] ?? 0) }}</div><div class="erp-stat-note">Toàn bộ hồ sơ</div></div></div>
<div class="erp-stat amber"><div class="erp-stat-icon"><i class="bi bi-hourglass-split"></i></div><div><div class="erp-stat-label">Chờ phê duyệt</div><div class="erp-stat-value">{{ number_format($stats['pending'] ?? 0) }}</div><div class="erp-stat-note">Sales, kế toán hoặc BGĐ</div></div></div>
<div class="erp-stat"><div class="erp-stat-icon"><i class="bi bi-box-seam"></i></div><div><div class="erp-stat-label">Đang xử lý kho</div><div class="erp-stat-value">{{ number_format($stats['warehouse'] ?? 0) }}</div><div class="erp-stat-note">Thu hồi, nhận và kiểm tra</div></div></div>
<div class="erp-stat red"><div class="erp-stat-icon"><i class="bi bi-cash-coin"></i></div><div><div class="erp-stat-label">Chờ tài chính</div><div class="erp-stat-value">{{ number_format($stats['refund'] ?? 0) }}</div><div class="erp-stat-note">Hoàn tiền hoặc cấn trừ</div></div></div>
</div>
<form method="get" class="erp-card erp-filter"><div class="erp-card-body"><div class="erp-filter-grid" style="grid-template-columns:minmax(280px,1.5fr) minmax(210px,1fr) auto"><div><label class="erp-label">Tìm kiếm</label><input class="erp-input" name="q" value="{{ request('q') }}" placeholder="Mã phiếu hoặc mã đơn..."></div><div><label class="erp-label">Trạng thái</label><select class="erp-select" name="status"><option value="">Tất cả trạng thái</option>@foreach($statusLabels as $k=>$v)<option value="{{ $k }}" @selected(request('status')===$k)>{{ $v }}</option>@endforeach</select></div><div class="erp-filter-actions"><div style="display:flex;gap:7px"><button class="erp-btn erp-btn-primary"><i class="bi bi-search"></i> Lọc</button>@if(request()->query())<a class="erp-btn" href="{{ route('order-returns.dashboard') }}"><i class="bi bi-x-lg"></i></a>@endif</div></div></div></div></form>
<div class="erp-card erp-desktop-table"><div class="erp-card-head"><div><h2 class="erp-card-title">Danh sách hồ sơ hậu mãi</h2><div class="erp-card-sub">{{ number_format($returns->total()) }} hồ sơ phù hợp</div></div></div><div class="erp-table-wrap"><table class="erp-table"><thead><tr><th>Mã phiếu</th><th>Đơn hàng & khách</th><th>Loại xử lý</th><th>Giá trị</th><th>Kho nhận</th><th>Trạng thái hàng</th><th>Tài chính</th><th>Người tạo</th><th></th></tr></thead><tbody>
@forelse($returns as $r)<tr><td><a class="erp-code" href="{{ route('order-returns.show',$r) }}">{{ $r->return_code ?: '#'.$r->id }}</a><div class="erp-secondary-text">{{ optional($r->created_at)->format('d/m/Y H:i') }}</div></td><td><a class="erp-primary-text" href="{{ route('orders.show',$r->order_id) }}">{{ $r->order->order_code ?? '#'.$r->order_id }}</a><div class="erp-secondary-text">{{ $r->order->lead->customer->name ?? 'Chưa có khách hàng' }}</div></td><td><span class="erp-badge blue">{{ $typeLabels[$r->type] ?? $r->type }}</span></td><td class="erp-money">{{ number_format((float)$r->total_return_amount,0,',','.') }} đ</td><td>{{ $r->receivingWarehouse->name ?? 'Chưa chọn' }}</td><td><span class="erp-badge {{ in_array($r->status,['completed','stocked_in'])?'green':(str_contains((string)$r->status,'pending')?'amber':'blue') }}">{{ $r->status_label ?? ($statusLabels[$r->status] ?? $r->status) }}</span><div class="erp-secondary-text">{{ $r->inventory_status ?? 'Chưa xử lý kho' }}</div></td><td><span class="erp-badge {{ ($r->financial_status??'')==='paid'?'green':'gray' }}">{{ $r->financial_status ?? 'Chưa xử lý' }}</span></td><td>{{ $r->requester->name ?? '—' }}</td><td><a class="erp-btn erp-btn-sm" href="{{ route('order-returns.show',$r) }}">Xem</a></td></tr>@empty<tr><td colspan="9"><div class="erp-empty"><div class="erp-empty-icon"><i class="bi bi-inbox"></i></div>Chưa có yêu cầu đổi trả.</div></td></tr>@endforelse
</tbody></table></div>@if($returns->hasPages())<div class="erp-pagination">{{ $returns->links() }}</div>@endif</div>
<div class="erp-mobile-list">@forelse($returns as $r)<div class="erp-mobile-card"><div class="erp-mobile-top"><div><a class="erp-code" href="{{ route('order-returns.show',$r) }}">{{ $r->return_code }}</a><div class="erp-secondary-text">Đơn {{ $r->order->order_code ?? '#'.$r->order_id }}</div></div><span class="erp-badge {{ in_array($r->status,['completed','stocked_in'])?'green':'amber' }}">{{ $r->status_label }}</span></div><div class="erp-mobile-grid"><div><div class="erp-mobile-k">Loại</div><div class="erp-mobile-v">{{ $typeLabels[$r->type] ?? $r->type }}</div></div><div><div class="erp-mobile-k">Giá trị</div><div class="erp-mobile-v">{{ number_format((float)$r->total_return_amount,0,',','.') }} đ</div></div><div><div class="erp-mobile-k">Kho</div><div class="erp-mobile-v">{{ $r->receivingWarehouse->name ?? 'Chưa chọn' }}</div></div><div><div class="erp-mobile-k">Người tạo</div><div class="erp-mobile-v">{{ $r->requester->name ?? '—' }}</div></div></div><a class="erp-btn erp-btn-primary" style="width:100%;margin-top:12px" href="{{ route('order-returns.show',$r) }}">Xem hồ sơ</a></div>@empty<div class="erp-empty">Chưa có hồ sơ.</div>@endforelse</div>
</div></div>
@endsection
