@extends('layouts.app')
@section('title','Hậu mãi đơn '.$order->order_code)
@section('content')
<link rel="stylesheet" href="{{ asset('css/orders-pro-v2.css') }}?v={{ @filemtime(public_path('css/orders-pro-v2.css')) ?: time() }}">
<script defer src="{{ asset('js/orders-pro-v2.js') }}?v={{ @filemtime(public_path('js/orders-pro-v2.js')) ?: time() }}"></script>
@php $active=$returns->whereNotIn('status',['completed','rejected','cancelled']);$typeLabels=['return'=>'Hoàn trả','exchange'=>'Đổi hàng','recall'=>'Thu hồi','cancel'=>'Hủy trước xuất kho']; @endphp
<div class="erp-page"><div class="erp-container"><div class="erp-page-head"><div><div class="erp-breadcrumb"><a href="{{ route('orders.show',$order) }}">Đơn {{ $order->order_code }}</a><span>/</span><strong>Hậu mãi</strong></div><h1 class="erp-title">Đổi trả & hoàn tiền</h1><div class="erp-subtitle">Quản lý toàn bộ yêu cầu hậu mãi của đơn hàng này.</div></div><div class="erp-head-actions"><a class="erp-btn" href="{{ route('orders.show',$order) }}"><i class="bi bi-arrow-left"></i> Chi tiết đơn</a><a class="erp-btn erp-btn-primary" href="{{ route('orders.returns.create',$order) }}"><i class="bi bi-plus-lg"></i> Tạo yêu cầu</a></div></div>
<div class="erp-summary"><div class="erp-summary-item"><div class="erp-summary-k">Đơn hàng</div><div class="erp-summary-v">{{ $order->order_code }}</div><div class="erp-summary-s">{{ $order->lead->customer->name ?? 'Chưa có khách hàng' }}</div></div><div class="erp-summary-item"><div class="erp-summary-k">Trạng thái kho</div><div class="erp-summary-v">{{ $order->inventory_issued?'Đã trừ tồn':'Chưa xuất kho' }}</div><div class="erp-summary-s">{{ $order->warehouse->name ?? 'Chưa chọn kho' }}</div></div><div class="erp-summary-item"><div class="erp-summary-k">Tổng yêu cầu</div><div class="erp-summary-v">{{ $returns->count() }}</div><div class="erp-summary-s">{{ $active->count() }} đang xử lý</div></div><div class="erp-summary-item"><div class="erp-summary-k">Tổng giá trị hoàn</div><div class="erp-summary-v">{{ number_format((float)$returns->sum('total_return_amount'),0,',','.') }} đ</div><div class="erp-summary-s">Theo các phiếu đã tạo</div></div><div class="erp-summary-item"><div class="erp-summary-k">Cảnh báo</div><div class="erp-summary-v">{{ $order->inventory_issued?'Phải nhận hàng thực tế':'Có thể hủy trước xuất' }}</div><div class="erp-summary-s">Không điều chỉnh tồn thủ công</div></div></div>
<div class="erp-card"><div class="erp-card-head"><div><h2 class="erp-card-title">Hồ sơ hậu mãi</h2><div class="erp-card-sub">{{ $returns->count() }} phiếu của đơn {{ $order->order_code }}</div></div></div><div class="erp-table-wrap"><table class="erp-table" style="min-width:900px"><thead><tr><th>Mã phiếu</th><th>Loại</th><th>Lý do</th><th>Giá trị</th><th>Kho nhận</th><th>Trạng thái</th><th>Ngày tạo</th><th></th></tr></thead><tbody>@forelse($returns as $r)<tr><td><a class="erp-code" href="{{ route('order-returns.show',$r) }}">{{ $r->return_code }}</a></td><td>{{ $typeLabels[$r->type]??$r->type }}</td><td>{{ \Illuminate\Support\Str::limit($r->reason_detail ?: $r->reason,70) }}</td><td class="erp-money">{{ number_format((float)$r->total_return_amount,0,',','.') }} đ</td><td>{{ $r->receivingWarehouse->name ?? 'Chưa chọn' }}</td><td><span class="erp-badge {{ in_array($r->status,['completed','stocked_in'])?'green':'amber' }}">{{ $r->status_label }}</span></td><td>{{ optional($r->created_at)->format('d/m/Y H:i') }}</td><td><a class="erp-btn erp-btn-sm" href="{{ route('order-returns.show',$r) }}">Xem</a></td></tr>@empty<tr><td colspan="8"><div class="erp-empty"><div class="erp-empty-icon"><i class="bi bi-arrow-left-right"></i></div>Đơn hàng chưa có yêu cầu hậu mãi.<div style="margin-top:12px"><a class="erp-btn erp-btn-primary" href="{{ route('orders.returns.create',$order) }}">Tạo yêu cầu đầu tiên</a></div></div></td></tr>@endforelse</tbody></table></div></div>
@if($order->inventory_issued)<div class="erp-alert erp-alert-warning" style="margin-top:14px"><strong>Đơn này đã xuất kho và trừ tồn.</strong> Không hủy hoặc cộng tồn trực tiếp. Hàng hoàn chỉ được nhập kho sau bước nhận và kiểm tra.</div>@endif
</div></div>
@endsection
