<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><title>Phiếu xuất kho {{ $voucherCode }}</title>
<style>@page{margin:35px 40px}*{font-family:"DejaVu Sans",sans-serif;box-sizing:border-box}body{color:#17304a;font-size:10px}.brand{color:#087c64;font-size:18px;font-weight:700}.brand-note{margin-top:4px;color:#708296;font-size:9px}.title{margin:25px 0 19px;text-align:center}.title h1{margin:0 0 5px;color:#087c64;font-size:20px}.title p{margin:0;color:#708296}.meta{width:100%;margin-bottom:18px;border-collapse:collapse}.meta td{width:50%;padding:6px 0}.meta span{color:#708296}.items{width:100%;border-collapse:collapse}.items th{padding:8px 6px;background:#087c64;color:white;font-size:9px;text-align:left}.items td{padding:8px 6px;border:1px solid #e1e8ed;vertical-align:top}.items .number{text-align:right;white-space:nowrap}.items .total td{background:#eef7f4;color:#087c64;font-weight:700}.note{margin-top:15px;color:#52677d}.signatures{width:100%;margin-top:35px;border-collapse:collapse;text-align:center}.signatures td{width:25%;vertical-align:top}.signatures strong{display:block;font-size:10px}.signatures span{display:block;margin-top:5px;color:#708296;font-size:8px}.footer{margin-top:78px;padding-top:9px;border-top:1px solid #e1e8ed;color:#708296;font-size:8px}</style>
</head><body>
<div class="brand">EGO SOLAR</div><div class="brand-note">Chứng từ xuất vật tư công trình / bảo hành</div>
<div class="title"><h1>PHIẾU XUẤT KHO</h1><p>Số phiếu: {{ $voucherCode }}</p></div>
<table class="meta"><tr><td><span>Công trình:</span> <strong>{{ $mr->site->name ?? '—' }}</strong></td><td><span>Kho xuất:</span> <strong>{{ $mr->warehouse->name ?? 'EGO_VN' }}</strong></td></tr><tr><td><span>Loại vật tư:</span> {{ $requestSource['label'] ?? 'Công trình mới' }}</td><td><span>Ngày xuất:</span> {{ optional($issuedAt)->format('d/m/Y H:i') }}</td></tr><tr><td><span>Người đề xuất:</span> {{ $requestSource['requester_name'] ?? $mr->creator->name ?? '—' }}</td><td><span>Mã công trình:</span> #{{ $mr->site_id }}</td></tr></table>
<table class="items"><thead><tr><th>STT</th><th>Sản phẩm thực xuất</th><th>SKU</th><th>SL</th><th>ĐVT</th><th>Giá vốn</th><th>Thành tiền</th></tr></thead><tbody>
@foreach($mr->items as $index => $item)
<tr><td>{{ $index + 1 }}</td><td>{{ $item->product->name ?? 'Sản phẩm #'.$item->product_id }}</td><td>{{ $item->product->sku ?? '#'.$item->product_id }}</td><td class="number">{{ rtrim(rtrim(number_format((float) $item->qty, 2, ',', '.'), '0'), ',') }}</td><td>{{ $item->unit ?? '—' }}</td><td class="number">{{ number_format((float) $item->unit_cost, 0, ',', '.') }}</td><td class="number">{{ number_format((float) ($item->line_total ?? ((float) $item->qty * (float) $item->unit_cost)), 0, ',', '.') }}</td></tr>
@endforeach
<tr class="total"><td colspan="6">TỔNG GIÁ TRỊ XUẤT KHO</td><td class="number">{{ number_format((float) ($mr->total_cost ?? collect($mr->items)->sum('line_total')), 0, ',', '.') }} đ</td></tr></tbody></table>
<p class="note"><strong>Ghi chú:</strong> {{ $mr->note ?: 'Không có ghi chú.' }}</p>
<table class="signatures"><tr><td><strong>Người lập phiếu</strong><span>(Ký, ghi rõ họ tên)</span></td><td><strong>Thủ kho</strong><span>(Ký, ghi rõ họ tên)</span></td><td><strong>Người nhận</strong><span>(Ký, ghi rõ họ tên)</span></td><td><strong>Kế toán</strong><span>(Ký, ghi rõ họ tên)</span></td></tr></table>
<p class="footer">Tạo từ hệ thống EGO Solar lúc {{ now()->format('H:i d/m/Y') }} · Phiếu {{ $voucherCode }}</p>
</body></html>
