@extends('layouts.app')
@section('title', 'Bảo hành kỹ thuật')
@push('styles')<link rel="stylesheet" href="{{ asset('css/technical-workspace.css') }}?v={{ filemtime(public_path('css/technical-workspace.css')) }}">@endpush
@section('content')
<div class="tw-page"><div class="tw-shell">
<section class="tw-hero"><div class="tw-kicker">PHÒNG KỸ THUẬT · O&M / BẢO HÀNH</div><h1>Bảo hành sau bàn giao</h1><p>Theo dõi thời hạn bảo hành, lịch bảo trì kế tiếp và người phụ trách theo từng công trình.</p>@include('technical.workspace.partials-nav')</section>
<section class="tw-kpis"><article class="tw-kpi"><span>Đang bảo hành</span><strong>{{ $summary['active'] }}</strong><small>Hồ sơ đang hiệu lực</small></article><article class="tw-kpi"><span>Đến hạn 30 ngày</span><strong>{{ $summary['due_30'] }}</strong><small>Cần lên lịch</small></article><article class="tw-kpi"><span>Bảo trì quá hạn</span><strong>{{ $summary['overdue'] }}</strong><small>Cần xử lý ngay</small></article><article class="tw-kpi"><span>Hết hạn bảo hành</span><strong>{{ $summary['expired'] }}</strong><small>Theo ngày kết thúc</small></article></section>
<section class="tw-card"><div class="tw-card__body"><form method="GET" class="tw-filter"><label>Tìm kiếm<input class="tw-input" type="search" name="q" value="{{ request('q') }}" placeholder="Mã, tên, khách hàng, địa chỉ..."></label><label>Trạng thái<select class="tw-select" name="status"><option value="">Tất cả</option><option value="active" @selected(request('status')==='active')>Đang hoạt động</option><option value="completed" @selected(request('status')==='completed')>Hoàn tất</option></select></label><button class="tw-btn"><i class="bi bi-search"></i>Lọc</button></form></div></section>
<section class="tw-card"><div class="tw-table-wrap"><table class="tw-table"><thead><tr><th>Công trình</th><th>Khách hàng/Địa chỉ</th><th>Thời hạn</th><th>Bảo trì kế tiếp</th><th>Phụ trách</th><th></th></tr></thead><tbody>@forelse($warranties as $item)@php($next=$item->next_maintenance_at ? \Carbon\Carbon::parse($item->next_maintenance_at) : null)<tr><td><div class="tw-name">{{ $item->code }} · {{ $item->name }}</div><div class="tw-sub">{{ $item->status }}</div></td><td><div>{{ $item->contact_name ?: 'Chưa có người liên hệ' }}</div><div class="tw-sub">{{ $item->address }}</div></td><td>{{ \Carbon\Carbon::parse($item->starts_at)->format('d/m/Y') }} → {{ \Carbon\Carbon::parse($item->ends_at)->format('d/m/Y') }}</td><td><span class="tw-status {{ !$next ? '' : ($next->isPast() ? 'is-overdue' : ($next->lte(now()->addDays(30)) ? 'is-due' : 'is-ok')) }}">{{ $next?->format('d/m/Y') ?: 'Chưa lên lịch' }}</span></td><td>{{ $item->assigned_name ?: 'Chưa phân công' }}</td><td><a class="tw-btn tw-btn--soft" href="{{ route('project-test.show',$item->project_id) }}">Mở hồ sơ</a></td></tr>@empty<tr><td colspan="6"><div class="tw-empty">Chưa có hồ sơ bảo hành phù hợp.</div></td></tr>@endforelse</tbody></table></div>@if($warranties->hasPages())<div class="tw-card__body">{{ $warranties->links() }}</div>@endif</section>
</div></div>
@endsection
