@extends('layouts.app')
@section('title', 'Đề nghị tạm ứng lương')
@push('styles')<link rel="stylesheet" href="{{ asset('css/ego-payment-advance-modules.css') }}?v=1">@endpush
@section('content')
<div class="container-fluid ego-advance-page">
    <div class="ego-advance-head"><div><h1 class="ego-advance-title">Đề nghị tạm ứng lương</h1><div class="ego-advance-sub">Phiếu tạm ứng lương đi cùng luồng duyệt DNTT và tự ghi nhận vào kỳ lương sau khi Kế toán chi.</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createSalaryAdvanceModal"><i class="bi bi-plus-lg me-1"></i>Tạo DNTUL</button></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="ego-advance-card mb-3"><div class="ego-advance-card__body"><form method="GET" class="row g-2 align-items-end"><div class="col-md-5"><label class="form-label">Tìm kiếm</label><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Mã phiếu, nhân viên, lý do..."></div><div class="col-md-3"><label class="form-label">Kỳ lương</label><input type="month" class="form-control" name="month" value="{{ request('month') }}"></div><div class="col-md-2"><label class="form-label">Trạng thái</label><select class="form-select" name="status"><option value="">Tất cả</option>@foreach($statusLabels as $k=>$v)<option value="{{ $k }}" @selected(request('status')===$k)>{{ $v }}</option>@endforeach</select></div><div class="col-md-2 d-grid"><button class="btn btn-outline-primary">Lọc</button></div></form></div></div>
    <div class="ego-advance-card"><div class="table-responsive"><table class="table table-hover mb-0 ego-advance-table"><thead><tr><th>Mã</th><th>Nhân viên</th><th>Kỳ lương</th><th>Lý do</th><th class="text-end">Số tiền</th><th>Trạng thái</th><th>Payroll</th><th></th></tr></thead><tbody>
    @forelse($items as $it)<tr><td><strong>{{ $it->code }}</strong><div class="small text-muted">{{ optional(\Carbon\Carbon::parse($it->payment_created_at))->format('d/m/Y') }}</div></td><td>{{ $it->employee_name ?: '—' }}</td><td>{{ $it->payroll_month }}</td><td style="min-width:240px">{{ \Illuminate\Support\Str::limit($it->reason,90) }}</td><td class="text-end ego-advance-money">{{ number_format($it->requested_amount) }} đ</td><td><span class="ego-advance-status {{ $it->status==='accounting_approved'?'is-good':(str_contains($it->status,'rejected')?'is-bad':'is-warn') }}">{{ $statusLabels[$it->status] ?? $it->status }}</span></td><td>@if($it->applied_to_payroll_at)<span class="ego-advance-status is-good">Đã ghi bảng lương</span>@else<span class="text-muted">Chưa ghi</span>@endif</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('salary_advances.show',$it->payment_request_id) }}">Xem</a></td></tr>@empty<tr><td colspan="8" class="text-center py-5 text-muted">Chưa có đề nghị tạm ứng lương.</td></tr>@endforelse
    </tbody></table></div>@if($items->hasPages())<div class="p-3">{{ $items->links() }}</div>@endif</div>
</div>
<div class="modal fade" id="createSalaryAdvanceModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('salary_advances.store') }}" enctype="multipart/form-data">@csrf<div class="modal-header"><h5 class="modal-title">Tạo đề nghị tạm ứng lương</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Kỳ lương <span class="text-danger">*</span></label><input type="month" name="payroll_month" class="form-control" required value="{{ old('payroll_month', now()->format('Y-m')) }}"></div><div class="col-md-6"><label class="form-label">Số tiền xin tạm ứng <span class="text-danger">*</span></label><input name="amount" class="form-control" inputmode="numeric" required value="{{ old('amount') }}"></div><div class="col-12"><label class="form-label">Lý do <span class="text-danger">*</span></label><textarea name="reason" class="form-control" rows="3" required>{{ old('reason') }}</textarea></div><div class="col-md-6"><label class="form-label">Ngày cần nhận</label><input type="date" name="needed_date" class="form-control" value="{{ old('needed_date') }}"></div><div class="col-md-6"><label class="form-label">Ngân hàng / STK / Chủ TK</label><input name="bank_info" class="form-control" value="{{ old('bank_info') }}"></div><div class="col-12"><label class="form-label">Chứng từ (nếu có)</label><input type="file" name="attachment" class="form-control"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Đóng</button><button class="btn btn-primary">Lưu nháp</button></div></form></div></div></div>
@endsection
