<?php

return [
    'company_id_resolver' => App\Support\EgoCompanyLock::class,

    'permissions' => [
        'use' => 'ai.use',
        'providers_manage' => 'ai.providers.manage',
        'audit_view' => 'ai.audit.view',
    ],

    'modules' => [
        'orders' => [
            'label' => 'Đơn hàng & công nợ',
            'permission' => 'ai.search.orders',
            'page_permissions' => ['page.orders'],
            'icon' => 'bi-receipt',
        ],
        'customers' => [
            'label' => 'Khách hàng',
            'permission' => 'ai.search.customers',
            'page_permissions' => ['page.customers'],
            'icon' => 'bi-people',
        ],
        'inventory' => [
            'label' => 'Sản phẩm & tồn kho',
            'permission' => 'ai.search.inventory',
            'page_permissions' => ['page.products', 'page.warehouses'],
            'icon' => 'bi-box-seam',
        ],
        'tasks' => [
            'label' => 'Công việc',
            'permission' => 'ai.search.tasks',
            'page_permissions' => ['page.tasks'],
            'icon' => 'bi-list-check',
        ],
        'sites' => [
            'label' => 'Công trình & bảo hành',
            'permission' => 'ai.search.sites',
            'page_permissions' => ['page.sites', 'page.technical'],
            'icon' => 'bi-building-gear',
        ],
        'payment_requests' => [
            'label' => 'Đề nghị thanh toán',
            'permission' => 'ai.search.payment_requests',
            'page_permissions' => ['page.payment_requests'],
            'icon' => 'bi-cash-stack',
        ],
        'attendance' => [
            'label' => 'Chấm công',
            'permission' => 'ai.search.attendance',
            'page_permissions' => [],
            'icon' => 'bi-person-check',
        ],
        'marketing' => [
            'label' => 'Marketing & lead',
            'permission' => 'ai.search.marketing',
            'page_permissions' => ['page.marketing'],
            'icon' => 'bi-megaphone',
        ],
        'hr' => [
            'label' => 'Nhân sự & tuyển dụng',
            'permission' => 'ai.search.hr',
            'page_permissions' => ['page.hr'],
            'icon' => 'bi-person-workspace',
        ],
    ],

    'daily_limits' => [
        'admin' => 1000,
        'management' => 500,
        'accounting' => 250,
        'sales_manager' => 250,
        'technical_manager' => 250,
        'marketing_manager' => 250,
        'hr' => 250,
        'warehouse' => 160,
        'sales' => 160,
        'ky_thuat' => 160,
        'marketing' => 160,
        'default' => 80,
    ],

    'role_scopes' => [
        'admin' => [
            '*' => 'company',
        ],
        'management' => [
            '*' => 'company',
        ],
        'accounting' => [
            'orders' => 'company',
            'customers' => 'none',
            'inventory' => 'company',
            'tasks' => 'self',
            'sites' => 'company',
            'payment_requests' => 'company',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'warehouse' => [
            'orders' => 'company',
            'customers' => 'none',
            'inventory' => 'company',
            'tasks' => 'self',
            'sites' => 'company',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'sales_manager' => [
            'orders' => 'department',
            'customers' => 'department',
            'inventory' => 'company',
            'tasks' => 'department',
            'sites' => 'department',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'sales' => [
            'orders' => 'self',
            'customers' => 'self',
            'inventory' => 'company',
            'tasks' => 'self',
            'sites' => 'self',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'technical_manager' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'company',
            'tasks' => 'department',
            'sites' => 'company',
            'payment_requests' => 'department',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'ky_thuat' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'company',
            'tasks' => 'self',
            'sites' => 'self',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
        'marketing_manager' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'none',
            'tasks' => 'department',
            'sites' => 'none',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'company',
            'hr' => 'none',
        ],
        'marketing' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'none',
            'tasks' => 'self',
            'sites' => 'none',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'self',
            'hr' => 'none',
        ],
        'hr' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'none',
            'tasks' => 'department',
            'sites' => 'none',
            'payment_requests' => 'self',
            'attendance' => 'company',
            'marketing' => 'none',
            'hr' => 'company',
        ],
        'default' => [
            'orders' => 'none',
            'customers' => 'none',
            'inventory' => 'none',
            'tasks' => 'self',
            'sites' => 'none',
            'payment_requests' => 'self',
            'attendance' => 'self',
            'marketing' => 'none',
            'hr' => 'none',
        ],
    ],

    'role_permission_matrix' => [
        'admin' => ['*'],
        'management' => [
            'ai.use', 'ai.search.orders', 'ai.search.customers', 'ai.search.inventory',
            'ai.search.tasks', 'ai.search.sites', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.search.marketing', 'ai.search.hr', 'ai.audit.view',
        ],
        'accounting' => [
            'ai.use', 'ai.search.orders', 'ai.search.inventory', 'ai.search.tasks',
            'ai.search.sites', 'ai.search.payment_requests', 'ai.search.attendance',
        ],
        'warehouse' => [
            'ai.use', 'ai.search.orders', 'ai.search.inventory', 'ai.search.tasks',
            'ai.search.sites', 'ai.search.payment_requests', 'ai.search.attendance',
        ],
        'sales_manager' => [
            'ai.use', 'ai.search.orders', 'ai.search.customers', 'ai.search.inventory',
            'ai.search.tasks', 'ai.search.sites', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.draft.orders', 'ai.draft.customers', 'ai.draft.tasks',
        ],
        'sales' => [
            'ai.use', 'ai.search.orders', 'ai.search.customers', 'ai.search.inventory',
            'ai.search.tasks', 'ai.search.sites', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.draft.orders', 'ai.draft.customers', 'ai.draft.tasks',
        ],
        'technical_manager' => [
            'ai.use', 'ai.search.inventory', 'ai.search.tasks', 'ai.search.sites',
            'ai.search.payment_requests', 'ai.search.attendance', 'ai.draft.tasks',
        ],
        'ky_thuat' => [
            'ai.use', 'ai.search.inventory', 'ai.search.tasks', 'ai.search.sites',
            'ai.search.payment_requests', 'ai.search.attendance', 'ai.draft.tasks',
        ],
        'marketing_manager' => [
            'ai.use', 'ai.search.tasks', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.search.marketing', 'ai.draft.tasks',
        ],
        'marketing' => [
            'ai.use', 'ai.search.tasks', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.search.marketing', 'ai.draft.tasks',
        ],
        'hr' => [
            'ai.use', 'ai.search.tasks', 'ai.search.payment_requests',
            'ai.search.attendance', 'ai.search.hr', 'ai.draft.tasks',
        ],
    ],

    'all_permissions' => [
        'ai.use',
        'ai.search.orders',
        'ai.search.customers',
        'ai.search.inventory',
        'ai.search.tasks',
        'ai.search.sites',
        'ai.search.payment_requests',
        'ai.search.attendance',
        'ai.search.marketing',
        'ai.search.hr',
        'ai.draft.orders',
        'ai.draft.customers',
        'ai.draft.tasks',
        'ai.draft.payment_requests',
        'ai.providers.manage',
        'ai.audit.view',
    ],
];
