<?php

return [
    'admin_roles' => ['admin'],

    /*
    | Khi một role chưa bật page_access_enabled, hệ thống giữ nguyên cách phân
    | quyền cũ để không khóa nhầm nhân sự đang sử dụng CRM.
    */
    'legacy_compatibility' => true,

    /*
    | Các quyền nhạy cảm luôn được kiểm tra từ backend,
    | kể cả role chưa bật toàn bộ ma trận quyền truy cập trang.
    */
    'always_enforce_permissions' => [
        'page.orders',
    ],

    'protected_roles' => [
        'admin',
        'management',
        'accounting',
        'warehouse',
        'sales',
        'sales_manager',
        'marketing',
        'marketing_manager',
        'ky_thuat',
        'technical_manager',
        'hr',
    ],

    /*
    | Chỉ các biểu thức role cấp module bên dưới mới được quyền dùng page.*
    | thay thế role cũ. Các route nhạy cảm như duyệt/xóa vẫn giữ lớp role hoặc
    | permission chuyên biệt đang có trong source.
    */
    'legacy_role_fallbacks' => [
        'marketing|marketing_manager|admin',
        'marketing|marketing_manager|admin|accounting',
        'ky_thuat|accounting|admin|warehouse|kho|sales',
        'ky_thuat|accounting|admin|warehouse|kho|sales|sales',
        'admin|accounting',
        'admin|accounting|manager',
        'ky_thuat|accounting|admin|manager',
        'ky_thuat|technical|technician|technical_staff|technical_leader|technical_manager|accounting|admin|manager|warehouse|kho|sales|sales_manager|cskh',
    ],

    'page_permissions' => [
        'page.dashboard' => [
            'label' => 'Dashboard điều hành',
            'description' => 'Xem trang tổng quan, chỉ số và cảnh báo điều hành.',
            'icon' => 'bi-speedometer2',
            'group' => 'Truy cập trang',
            'routes' => ['dashboard'],
            'exact_paths' => ['/'],
            'path_prefixes' => [],
        ],
        'page.booking' => [
            'label' => 'Booking phòng họp',
            'description' => 'Xem và thao tác module đặt phòng họp.',
            'icon' => 'bi-calendar2-check',
            'group' => 'Truy cập trang',
            'routes' => ['meeting-room-bookings.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/booking-phong-hop'],
        ],
        'page.customers' => [
            'label' => 'Khách hàng',
            'description' => 'Truy cập danh sách khách hàng và hồ sơ khách hàng.',
            'icon' => 'bi-people',
            'group' => 'Truy cập trang',
            'routes' => ['customers.*', 'customer-profiles.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/customers', '/customer-profiles'],
        ],
        'page.orders' => [
            'label' => 'Đơn hàng & Báo giá',
            'description' => 'Truy cập đơn hàng, báo giá, đổi trả và hoàn tiền.',
            'icon' => 'bi-receipt',
            'group' => 'Truy cập trang',
            'routes' => ['orders.*', 'sales-quotations.*', 'order-returns.*', 'order-refunds.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/orders', '/bao-gia', '/order-returns', '/order-refunds'],
        ],
        'page.sites' => [
            'label' => 'Công trình & Đơn vật tư',
            'description' => 'Truy cập công trình, lắp ráp và quy trình đơn vật tư.',
            'icon' => 'bi-building-gear',
            'group' => 'Truy cập trang',
            'routes' => ['sites.*', 'sites-v2.*', 'project-test.*', 'material-requests.*', 'site-assemblies.*'],
            'exact_paths' => ['/theo-doi-trang-thai'],
            'path_prefixes' => ['/cong-trinh', '/cong-trinh-moi', '/cong-trinh-test-new', '/don-vat-tu'],
        ],
        'page.payment_requests' => [
            'label' => 'Đề nghị thanh toán',
            'description' => 'Truy cập danh sách, chi tiết và hồ sơ đề nghị thanh toán.',
            'icon' => 'bi-cash-stack',
            'group' => 'Truy cập trang',
            'routes' => ['payment_requests.*', 'payment-requests.*', 'payment-attachments.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/payment-requests'],
        ],
        'page.proposals' => [
            'label' => 'Đề xuất nội bộ',
            'description' => 'Truy cập module đề xuất và quy trình phê duyệt.',
            'icon' => 'bi-lightbulb',
            'group' => 'Truy cập trang',
            'routes' => ['de-xuat.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/de-xuat'],
        ],
        'page.technical' => [
            'label' => 'Kỹ thuật & Bảo hành',
            'description' => 'Truy cập kỹ thuật, bảo trì, bảo hành và serial.',
            'icon' => 'bi-tools',
            'group' => 'Truy cập trang',
            'routes' => ['ky-thuat.*', 'serial-warranty.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/ky-thuat', '/serial-warranty'],
        ],
        'page.sales' => [
            'label' => 'Sales',
            'description' => 'Truy cập KPI, hoa hồng và báo cáo công việc Sales.',
            'icon' => 'bi-graph-up-arrow',
            'group' => 'Truy cập trang',
            'routes' => ['sales.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/sales'],
        ],
        'page.marketing' => [
            'label' => 'Marketing',
            'description' => 'Truy cập kế hoạch, chiến dịch, lead, KPI và báo cáo Marketing.',
            'icon' => 'bi-megaphone',
            'group' => 'Truy cập trang',
            'routes' => ['marketing.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/marketing'],
        ],
        'page.tasks' => [
            'label' => 'Công việc',
            'description' => 'Truy cập danh sách, giao việc và kết quả công việc.',
            'icon' => 'bi-list-check',
            'group' => 'Truy cập trang',
            'routes' => ['tasks.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/chat/tasks'],
        ],
        'page.products' => [
            'label' => 'Sản phẩm',
            'description' => 'Truy cập sản phẩm, danh mục, thương hiệu, bảng giá và nhập hàng.',
            'icon' => 'bi-box-seam',
            'group' => 'Truy cập trang',
            'routes' => ['products.*', 'categories.*', 'brands.*', 'price-tiers.*', 'media.*', 'product-goods-receipts.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/products', '/san-pham-kho', '/categories', '/brands', '/price-tiers', '/media'],
        ],
        'page.warehouses' => [
            'label' => 'Kho hàng',
            'description' => 'Truy cập kho, tồn kho và kiểm kê.',
            'icon' => 'bi-boxes',
            'group' => 'Truy cập trang',
            'routes' => ['warehouses.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/warehouses'],
        ],
        'page.finance' => [
            'label' => 'Tài chính',
            'description' => 'Truy cập công nợ, thu chi, tài khoản, ngân sách và báo cáo tài chính.',
            'icon' => 'bi-bank',
            'group' => 'Truy cập trang',
            'routes' => ['finance.*', 'payment-methods.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/finance', '/payment-methods'],
        ],
        'page.hr' => [
            'label' => 'Nhân sự',
            'description' => 'Truy cập nhân sự, tuyển dụng, hồ sơ, chấm công và hành chính.',
            'icon' => 'bi-person-workspace',
            'group' => 'Truy cập trang',
            'routes' => ['hr.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/nhan-su', '/hr'],
        ],
        'page.chat' => [
            'label' => 'Tin nhắn',
            'description' => 'Truy cập hội thoại và tin nhắn nội bộ.',
            'icon' => 'bi-chat-dots',
            'group' => 'Truy cập trang',
            'routes' => ['chat.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/chat'],
            'exclude_prefixes' => ['/chat/tasks'],
        ],
        'page.company' => [
            'label' => 'Công ty & Pháp nhân',
            'description' => 'Truy cập quản lý công ty, pháp nhân và tài liệu doanh nghiệp.',
            'icon' => 'bi-buildings',
            'group' => 'Truy cập trang',
            'routes' => ['company-management.*', 'companies.*', 'company-documents.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/company-management', '/companies', '/company-documents'],
        ],
        'page.solar' => [
            'label' => 'Công cụ Solar',
            'description' => 'Truy cập tính toán và cấu hình công cụ Solar.',
            'icon' => 'bi-sun',
            'group' => 'Truy cập trang',
            'routes' => ['solar.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/solar'],
        ],
        'page.users' => [
            'label' => 'Quản lý người dùng',
            'description' => 'Truy cập danh sách và biểu mẫu tài khoản người dùng.',
            'icon' => 'bi-person-gear',
            'group' => 'Truy cập trang',
            'routes' => ['users.index', 'users.create', 'users.store', 'users.edit', 'users.update', 'users.destroy'],
            'exact_paths' => [],
            'path_prefixes' => ['/users'],
        ],
        'page.settings' => [
            'label' => 'Cài đặt hệ thống',
            'description' => 'Truy cập trung tâm cài đặt, vai trò, quyền trang, quyền menu và nhật ký.',
            'icon' => 'bi-shield-lock',
            'group' => 'Truy cập trang',
            'routes' => ['admin.settings.*', 'admin.role-permissions.*'],
            'exact_paths' => [],
            'path_prefixes' => ['/cai-dat'],
        ],
    ],


    /*
    |--------------------------------------------------------------------------
    | Quyền hiển thị menu
    |--------------------------------------------------------------------------
    | menu.* chỉ quyết định mục nào xuất hiện trong sidebar.
    | page.* mới là lớp chặn truy cập URL ở backend.
    */
    'menu_permissions' => [
        'menu.dashboard' => [
            'label' => 'Trang chủ',
            'description' => 'Hiển thị Dashboard trong sidebar.',
            'icon' => 'bi-house-door',
            'page_permission' => 'page.dashboard',
        ],
        'menu.booking' => [
            'label' => 'Booking phòng họp',
            'description' => 'Hiển thị module đặt phòng họp.',
            'icon' => 'bi-calendar2-check',
            'page_permission' => 'page.booking',
        ],
        'menu.customers' => [
            'label' => 'Khách hàng',
            'description' => 'Hiển thị nhóm menu khách hàng.',
            'icon' => 'bi-people',
            'page_permission' => 'page.customers',
        ],
        'menu.orders' => [
            'label' => 'Đơn hàng',
            'description' => 'Hiển thị nhóm menu đơn hàng và báo giá.',
            'icon' => 'bi-receipt',
            'page_permission' => 'page.orders',
        ],
        'menu.project_test' => [
            'label' => 'Công Trình Test new',
            'description' => 'Hiển thị quy trình công trình thử nghiệm mới.',
            'icon' => 'bi-diagram-3',
            'page_permission' => 'page.sites',
        ],
        'menu.sites' => [
            'label' => 'Công trình',
            'description' => 'Hiển thị công trình, đơn vật tư và lắp ráp.',
            'icon' => 'bi-building-gear',
            'page_permission' => 'page.sites',
        ],
        'menu.payment_requests' => [
            'label' => 'Đề nghị thanh toán',
            'description' => 'Hiển thị đề nghị thanh toán.',
            'icon' => 'bi-cash-stack',
            'page_permission' => 'page.payment_requests',
        ],
        'menu.proposals' => [
            'label' => 'Đề xuất',
            'description' => 'Hiển thị đề xuất nội bộ.',
            'icon' => 'bi-lightbulb',
            'page_permission' => 'page.proposals',
        ],
        'menu.technical' => [
            'label' => 'Kỹ thuật',
            'description' => 'Hiển thị kỹ thuật, bảo trì và bảo hành.',
            'icon' => 'bi-tools',
            'page_permission' => 'page.technical',
        ],
        'menu.sales' => [
            'label' => 'Sales',
            'description' => 'Hiển thị KPI, hoa hồng và báo cáo Sales.',
            'icon' => 'bi-graph-up-arrow',
            'page_permission' => 'page.sales',
        ],
        'menu.marketing' => [
            'label' => 'Marketing',
            'description' => 'Hiển thị kế hoạch và báo cáo Marketing.',
            'icon' => 'bi-megaphone',
            'page_permission' => 'page.marketing',
        ],
        'menu.tasks' => [
            'label' => 'Công việc',
            'description' => 'Hiển thị việc của tôi và giao việc.',
            'icon' => 'bi-list-check',
            'page_permission' => 'page.tasks',
        ],
        'menu.products' => [
            'label' => 'Sản phẩm',
            'description' => 'Hiển thị sản phẩm, kho và nhập xuất.',
            'icon' => 'bi-box-seam',
            'page_permission' => 'page.products',
        ],
        'menu.finance' => [
            'label' => 'Tài chính',
            'description' => 'Hiển thị công nợ, thu chi và báo cáo tài chính.',
            'icon' => 'bi-bank',
            'page_permission' => 'page.finance',
        ],
        'menu.company' => [
            'label' => 'Hồ sơ công ty',
            'description' => 'Hiển thị hồ sơ pháp nhân và tài liệu công ty.',
            'icon' => 'bi-folder2-open',
            'page_permission' => 'page.company',
        ],
        'menu.hr' => [
            'label' => 'Nhân sự',
            'description' => 'Hiển thị tuyển dụng, hồ sơ và chấm công.',
            'icon' => 'bi-person-workspace',
            'page_permission' => 'page.hr',
        ],
        'menu.settings' => [
            'label' => 'Cài đặt',
            'description' => 'Hiển thị trung tâm Cài đặt hệ thống.',
            'icon' => 'bi-gear',
            'page_permission' => 'page.settings',
        ],
    ],

    'group_labels' => [
        'lead' => ['label' => 'Lead', 'icon' => 'bi-person-plus'],
        'customer' => ['label' => 'Khách hàng', 'icon' => 'bi-people'],
        'order' => ['label' => 'Đơn hàng', 'icon' => 'bi-receipt'],
        'orders' => ['label' => 'Đổi trả & Hoàn tiền', 'icon' => 'bi-arrow-left-right'],
        'payment' => ['label' => 'Thanh toán', 'icon' => 'bi-cash-stack'],
        'product' => ['label' => 'Sản phẩm', 'icon' => 'bi-box-seam'],
        'products' => ['label' => 'Sản phẩm', 'icon' => 'bi-box-seam'],
        'categories' => ['label' => 'Danh mục', 'icon' => 'bi-tags'],
        'brands' => ['label' => 'Thương hiệu', 'icon' => 'bi-award'],
        'price-tiers' => ['label' => 'Bảng giá', 'icon' => 'bi-currency-dollar'],
        'warehouse' => ['label' => 'Kho hàng', 'icon' => 'bi-boxes'],
        'site' => ['label' => 'Công trình', 'icon' => 'bi-building-gear'],
        'material_request' => ['label' => 'Đơn vật tư', 'icon' => 'bi-clipboard-check'],
        'report' => ['label' => 'Báo cáo', 'icon' => 'bi-bar-chart'],
        'user' => ['label' => 'Người dùng', 'icon' => 'bi-person-gear'],
        'maintenance' => ['label' => 'Bảo trì/Bảo hành', 'icon' => 'bi-tools'],
        'settings' => ['label' => 'Quản trị hệ thống', 'icon' => 'bi-gear'],
    ],

    'action_labels' => [
        'view' => 'Xem',
        'view_all' => 'Xem tất cả',
        'view_own' => 'Xem dữ liệu của mình',
        'view_sales_all' => 'Xem toàn bộ Sales',
        'view_sales' => 'Xem Sales',
        'view_status' => 'Xem trạng thái',
        'view_warehouse' => 'Xem cho kho',
        'create' => 'Tạo mới',
        'update' => 'Cập nhật',
        'update_all' => 'Cập nhật tất cả',
        'update_own' => 'Cập nhật dữ liệu của mình',
        'update_sales' => 'Cập nhật Sales',
        'delete' => 'Xóa',
        'approve' => 'Duyệt',
        'reject' => 'Từ chối',
        'submit' => 'Gửi duyệt',
        'assign' => 'Phân công',
        'manage' => 'Quản lý',
        'export' => 'Xuất dữ liệu',
        'stock_check' => 'Kiểm kho',
        'stock_update' => 'Cập nhật tồn kho',
        'mark_paid' => 'Đánh dấu đã thanh toán',
        'force_approve' => 'Duyệt cưỡng bức',
        'approve_level1' => 'Duyệt cấp 1',
        'approve_level2' => 'Duyệt cấp 2',
        'approve_accounting' => 'Kế toán duyệt',
        'request_revision' => 'Yêu cầu chỉnh sửa',
        'reopen' => 'Mở lại',
        'restore' => 'Khôi phục',
        'upload' => 'Tải lên',
        'download' => 'Tải xuống',
        'inspect' => 'Kiểm tra',
        'receive' => 'Tiếp nhận',
        'stock_in' => 'Nhập kho',
        'process' => 'Xử lý',
        'rate' => 'Đánh giá',
        'convert' => 'Chuyển đổi',
        'check_debt' => 'Kiểm tra công nợ',
    ],
];
